// Generated by CoffeeScript 1.7.1
spa.data = (function() {
  var getSio, initModule, makeSio, stateMap;
  stateMap = {
    sio: null
  };
  makeSio = function() {
    var socket;
    socket = io.connect('/chat');
    return {
      emit: function(event_name, data) {
        socket.emit(event_name, data);
      },
      on: function(event_name, callback) {
        socket.on(event_name, function() {
          callback(arguments);
        });
      }
    };
  };
  getSio = function() {
    if (!stateMap.sio) {
      stateMap.sio = makeSio();
    }
    return stateMap.sio;
  };
  initModule = function() {};
  return {
    getSio: getSio,
    initModule: initModule
  };
})();
